- name: Workflow Housekeeper
  # You may pin to the exact commit or the version.
  # uses: JosiahSiegel/workflow-housekeeper@f73f78d6cd72f7e6552ddc40838d12922d5dded2
  uses: JosiahSiegel/workflow-housekeeper@v1.0.4
  with:
    # Ignore runs from workflows currently in ./github/workflow
    ignore-branch-workflows: # optional
    # Period of time to maintain history. E.g. "2 weeks", "3 days", etc.
    retention-time: # optional
    # Number of latest runs to keep
    retain-run-count: # optional
    # Only list runs pending deletion
    dry-run: # optional
